### ISSUE TITLE
Add Bounty and Maltesers Products

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#11]
We need somebody to add the products **BOUNTY Twin Pack** and **MALTESERS** (these are the product names) to the project.

These products can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here are some helpful link:
http://www.marschocolate.com.au/products/bounty/bounty-twin-pack/
http://www.marschocolate.com.au/products/maltesers/maltesers-40g/

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by kwinzig** [comment]
I want to work on this issue :)

**Comment by KAUTH** [comment]
@kwinzig thanks a lot!! You are assigned this issue. Feel free to ask any question.

**Comment by kwinzig** [comment]
Split up #13  into two pull requests  (#15  and #16)
