### ISSUE TITLE
Add Coca-Cola Classic

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#14]
We need somebody to add the product **Coca-Cola Classic** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here is a helpful link:
http://www.coca-cola.co.uk/drinks/coca-cola/coca-cola

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by exler** [comment]
On my way.

**Comment by harshit98** [comment]
@KAUTH I would like to work on this. 👍

**Comment by KAUTH** [comment]
@harshit98 that's great. Thanks for the contribution!!
