### ISSUE TITLE
Add Coca-Cola Zero Sugar

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#18]
We need somebody to add the product **Coca-Cola Zero Sugar** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here is a helpful link:
http://www.coca-cola.co.uk/drinks/coca-cola-zero/coke-zero

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by pranaygupta36** [comment]
I would like to work on this issue.

**Comment by KAUTH** [comment]
Ok @pranaygupta36, thanks for contributing!! I am assigning you this issue. Ask freely if any problem comes up.
