### ISSUE TITLE
Add Diet Coke

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#23]
We need somebody to add the product **Diet Coke** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here is a helpful link:
http://www.coca-cola.co.uk/drinks/diet-coke/diet-coke

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by johnalaschober** [comment]
I'm going to try this as a "first pull request". Thanks!

**Comment by KAUTH** [comment]
@Caseyfam thanks! If you need any help let me know
