### ISSUE TITLE
Add Fanta Orange

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#30]
We need somebody to add the product **Fanta Orange** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here is a helpful link:
http://www.coca-cola.co.uk/drinks/fanta/fanta-orange

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by dkarakay** [comment]
I can do that

**Comment by KAUTH** [comment]
@dkarakay thanks a lot for the contribution!! If anything comes up ask freely.
