### ISSUE TITLE
Add Hygiene Product (mouthwash) to Product Crawler

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#4]
We need somebody to add the product **LISTERINE COOL MINT Zero Alcohol** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Hygiene_.
Here is a helpful link:
https://www.listerine.com/products/listerine-zero/listerine-cool-mint-zero-alcohol#inactive-ingredients

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by sayak119** [comment]
@KAUTH I would like to work on this issue

**Comment by KAUTH** [comment]
@sayak119 that is great, you are assigned this issue. If you have any questions I would be happy to help.
Thanks for contributing!!

**Comment by sayak119** [comment]
@KAUTH created a PR please review

**Comment by KAUTH** [comment]
@sayak119 PR looks great, we will merge soon. 
Thanks for your quick response!!
Are you interested in integrating other Listerine products or other mouthwash brands perhaps?

**Comment by sayak119** [comment]
Yes @KAUTH

**Comment by KAUTH** [comment]
@sayak119 The PR has been reviewed and it will be merged in Sunday (October 1st) and we will also renew the database in the Product Crawler website https://productcrawler.wixsite.com/home, so you can see your contribution there as well.
Thanks again for accepting to integrate even more products.

**Comment by sayak119** [comment]
@KAUTH you are doing a very good job here raising customer awareness. I will be glad to help you out.

**Comment by KAUTH** [comment]
@sayak119 thanks, your contribution is valuable to us, we need all the help we can get to make this project even more significant. Spread the word!!
