### ISSUE TITLE
Add Colgate Total Advanced Deep Clean Toothpaste

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#41]
We need somebody to add the product **Colgate Total Advanced Deep Clean Toothpast**e (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Hygiene_.
Here is a helpful link:
http://www.colgatetotal.com/health-benefits/toothpaste-ingredients

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by mahval** [comment]
I'll do it!

**Comment by KAUTH** [comment]
@mahval thanks!! Also check out our app https://play.google.com/store/apps/details?id=appeiro.productcrawler

**Comment by KAUTH** [comment]
@mahval if you need any help ask freely. Thanks!!

**Comment by mahval** [comment]
@KAUTH Thank you. I don't think I'll have any issues, just got busy yesterday. I'll do it tonight!!
