### ISSUE TITLE
git clone shows most files as deleted

### ISSUE THREAD

**Issue by Abhinay1997** [ProductCrawler/product_crawler#42]
Hello. I have been trying to understand what's going on. Can someone explain?
`git clone https://github.com/ProductCrawler/product_crawler` and even my fork
`git clone https://github.com/Abhinay1997/product_crawler` results in 
![clone](https://user-images.githubusercontent.com/24771261/31119506-ecafcf18-a84e-11e7-8897-f61020f4b55a.png)
![status](https://user-images.githubusercontent.com/24771261/31119505-ecae564c-a84e-11e7-90ae-06517b73b5e2.png)
Note: The warning about the Dove directory is because windows can't use ':' in its directory names.
I'm on windows 7 64-bit, the auto.crlf is set to true and I also enabled long paths using core.longpaths=true while cloning. Currently using git for windows.

Found no solution on stackoverflow. Am I missing something?

**Comment by KAUTH** [comment]
@Abhinay1997, sorry but I don't know what the problem is...

**Comment by Abhinay1997** [comment]
That's Ok, @KAUTH. I thought someone else might be facing this, so I just asked.

**Comment by KAUTH** [comment]
@Abhinay1997 if you still can't find an answer reopen the issue, maybe somebody can help.
