### ISSUE TITLE
Add DETTOL ANTISEPTIC LIQUID (CANADA)

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#52]
We need somebody to add the product **DETTOL ANTISEPTIC LIQUID** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Hygiene_.
Here is a helpful link:
http://rbnainfo.com/productpro/ProductSearch.do?brandId=12&productLineId=273&searchType=PL&template=1
Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by danielsouzaaf** [comment]
I'm working on this

**Comment by danielsouzaaf** [comment]
Mentioned in PR #53

**Comment by KAUTH** [comment]
@danielsouzaaf very good job, thaks for the contribution!! Just keep in mind that the png picture should be a picture of the info label or a screenshot of the product's label info

**Comment by danielsouzaaf** [comment]
Thank you for the feedback
