### ISSUE TITLE
Add MILKY WAY Single Bar (25g)

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#56]
We need somebody to add the product **MILKY WAY Single Bar (25g)** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here is a helpful link:
http://www.marschocolate.com.au/products/mms/mm%E2%80%99s-milk-chocolates-49g/

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by napcae** [comment]
I'll do it

**Comment by KAUTH** [comment]
@napcae thanks, but somebody has already done it. You can do however the previews issue.
