### ISSUE TITLE
Add SNICKERS Bar (36g)

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#59]
We need somebody to add the product **SNICKERS Bar (36g)** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here is a helpful link:
http://www.marschocolate.com.au/products/snickers/snickers-bar-36g/

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by Asutosh989** [comment]
Hi @KAUTH I would like to do this.

**Comment by robertoduessmann** [comment]
I'll work in this :)
