### ISSUE TITLE
Add CELEBRATIONS (300g)

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#60]
We need somebody to add the product **CELEBRATIONS (300g)** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages._
Here is a helpful link:
http://www.marschocolate.com.au/products/celebrations/celebrations-gift-box-300g/

Read the README.md and CONTRIBUTING.md before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by PallaviDas07** [comment]
I am interested. Can I start right away?

**Comment by KAUTH** [comment]
@PallaviDas07 thanks for the interest!! Yes you may

**Comment by PallaviDas07** [comment]
Thanks

**Comment by PallaviDas07** [comment]
Please review my PR #64
