### ISSUE TITLE
Add PODS with MARS (160g)

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#61]
We need somebody to add the product **PODS with MARS (160g)** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here is a helpful link:
http://www.marschocolate.com.au/products/pods/pods-with-mars/
Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by robertoduessmann** [comment]
I'd like to help. I'll work in this :smile:

**Comment by KAUTH** [comment]
@robertoduessmann that's great, thanks for the contribution!!
