### ISSUE TITLE
Add Hygiene Product (shampoo) to Product Crawler

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#7]
We need somebody to add the product **Dove Cool Moisture Shampoo** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Hygiene_.
Here is a helpful link:
https://www.dove.com/us/en/hair-care/shampoo/cool-moisture-shampoo.html

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by alecmatthews** [comment]
I'll pick this issue up.

**Comment by KAUTH** [comment]
@alec500oo that is great, I am assigning you this issue. If you have any questions ask freely.
Thanks for contributing!!
