### ISSUE TITLE
Add Budweiser

### ISSUE THREAD

**Issue by KAUTH** [ProductCrawler/product_crawler#77]
We need somebody to add the product **Budweiser** (this is the product name) to the project.

This product can be categorized into the **Product Type** of _Food, Drinks & Beverages_.
Here is a helpful link:
http://www.budweiser.com/en/our-beers/budweiser.html

Read the **README.md** and **CONTRIBUTING.md** before making a PR and contributing.

Thanks for taking the time to contribute to our project, we appreciate your help! 🌟

**Comment by rchioreanu** [comment]
working on it

**Comment by KAUTH** [comment]
@rchioreanu thanks for the contribution!! We will review it soon.
